version: "3"
services:

    flask:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        environment:
            FLASK_APP: project/__init__.py
            FLASK_ENV: development
        env_file: local.env
        depends_on:
            - "mongodb"
        volumes:
            - ".:/app"

    mongodb:
        image: "mongo"
        container_name: mongodb
        ports:
            - "27017:27017"
        volumes:
            - "/data/db"
        environment:
            MONGO_INITDB_ROOT_USERNAME: dontchat-admin
            MONGO_INITDB_ROOT_PASSWORD: dontchat-admin
            MONGO_INITDB_DATABASE: dontchatdb

